### ISSUE TITLE
[Error: Invalid oauth data: {"key":"access","reason":"Not validate key access"}]

### ISSUE THREAD

**Issue by 0xshuwei** [node-weixin/node-weixin-express#1]
➜  node_modules  weixin --id wxcdcdb6fe90c361xx --secret  b8e0e5d31a818c0abdc468fb8ad0fxxx --token AUTH_YOUR_TOKEN --jssdk-url http://baidu.com                    
Auth Ack And JSSDK Server Ready!
[Error: Invalid oauth data: {"key":"access","reason":"Not validate key access"}]
Failed to init Oauth Server!
Weixin Express Server Running on Port 3333

**Comment by calidion** [comment]
请参考：
https://github.com/node-weixin/node-weixin-express/wiki/express-v0.2%E7%9A%84%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8
