### ISSUE TITLE
weixin  /usr/local/bin/weixin: line 1: //#!/usr/bin/env: No such file or directory /usr/local/bin/weixin: line 3: syntax error near unexpected token `(' /usr/local/bin/weixin: line 3: `var meow = require('meow');'

### ISSUE THREAD

**Issue by 0xshuwei** [node-weixin/node-weixin-express#2]
![image](https://cloud.githubusercontent.com/assets/5377786/12047666/3495ea5a-af0a-11e5-8af4-12b5d0f58a95.png)

**Comment by 0xshuwei** [comment]
![image](https://cloud.githubusercontent.com/assets/5377786/12047852/6d7dcac4-af0d-11e5-9285-3ac627fc8101.png)
默认安装只是0.1.3，按照wiki 甚至都不能安装成功。。。

**Comment by calidion** [comment]
已经发布最新版本[node-weixin-express@0.2.0-alpha-3](https://github.com/node-weixin/node-weixin-express/tree/v0.2)，以解决你碰到的问题。
谢谢反馈。

**Comment by 0xshuwei** [comment]
![image](https://cloud.githubusercontent.com/assets/5377786/12048793/988f89b6-af1a-11e5-80fe-c998015349f7.png)

**Comment by 0xshuwei** [comment]
以我的环境需要同时另行安装 ejs  node-weixin-settings lodash  validator 这几个包组件

**Comment by calidion** [comment]
npm版本需要大于3.
npm --version
看看。

**Comment by calidion** [comment]
@0xshuwei 如果还有问题欢迎继续反馈。先关闭这个issue.
