### ISSUE TITLE
不能跑了？

### ISSUE THREAD

**Issue by hongtoushizi** [node-weixin/node-weixin-express#4]
演示站都报502了，并且程序跑不通啊？
![image](https://cloud.githubusercontent.com/assets/4995208/15239770/c4815e16-1917-11e6-8c19-d7ef15eeec62.png)

![image](https://cloud.githubusercontent.com/assets/4995208/15239785/d44a3930-1917-11e6-9f66-d79c24f4a5c5.png)

**Comment by calidion** [comment]
还可以跑的。
演示站是因为淘宝回收了资源，所以无法显示了。

**Comment by hongtoushizi** [comment]
@calidion  那我的那个error信息怎么解决呢？

**Comment by calidion** [comment]
@hongtoushizi 

没看README的结果。
直接打命令: 
weixin即可
``` bash
 weixin
```
或者指定端口号
```bash
 weixin --port 8081
```

不需要在命令行里填写id与secret。
