### ISSUE TITLE
nginx 反向代理错误

### ISSUE THREAD

**Issue by wpchou** [node-weixin/node-weixin-express#8]
直接npm install -g，运行weixin
connect failed (111: Connection refused) while connecting to upsteam
环境：
CentOS 7.2.1511
nginx: 1.6.3
node: v6.3.1
nginx 代理其它应用正常，不知道是不是个例。

**Comment by calidion** [comment]
需要先确保weixin已经正确运行。

**Comment by wpchou** [comment]
确认可以。

**Comment by calidion** [comment]
可以通过localtunnel测试一下。

**Comment by calidion** [comment]
如果测试通过，可能是你的nginx配置有问题。

**Comment by calidion** [comment]
先关闭了。如果有问题再重新开。
